# Generated by Django 4.0 on 2022-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
