# Generated by Django 4.0 on 2022-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_roommember_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
