# Generated by Django 4.0 on 2022-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_status_status_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
