# Generated by Django 4.0 on 2022-01-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_roommember_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
