# Generated by Django 4.0 on 2022-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_roommember_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
