# Generated by Django 4.0 on 2022-01-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_roommember_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('private', 'private'), ('group', 'group')], default='private', max_length=20),
        ),
    ]
