# Generated by Django 4.0 on 2022-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='status',
            field=models.CharField(choices=[('left', 'left'), ('active', 'active')], default='active', max_length=20),
        ),
    ]
