# Generated by Django 4.0 on 2022-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_roommember_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='closed',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='closed', max_length=20),
        ),
    ]
