# Generated by Django 4.0 on 2022-02-06 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0022_alter_roommember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='status',
            field=models.CharField(choices=[('left', 'left'), ('left_and_deleted', 'left_and_deleted'), ('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('blocked', 'blocked'), ('blocked_and_deleted', 'blocked_and_deleted')], default='inactive', max_length=40),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='auth.user')),
            ],
        ),
    ]
