# Generated by Django 4.0 on 2022-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_roommember_status_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=20),
        ),
    ]
