# Generated by Django 4.0 on 2022-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_roommember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('silent', 'silent'), ('removed', 'removed')], default='default', max_length=40),
        ),
    ]
