# Generated by Django 4.0 on 2022-01-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_alter_contactlist_contacts_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contactlist', to='auth.user'),
        ),
    ]
