# Generated by Django 4.0 on 2022-01-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0006_alter_contactlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='auth.user'),
        ),
    ]
